apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-platform
spec:
  project: infra
  source:
    repoURL: 'https://github.com/kenthua/gitops'
    path: infra/argocd/overlays/gcp
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
